### ISSUE TITLE
00 - gulp-serve-dist-error

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#14]
![00 - gulp-serve-dist-error](https://cloud.githubusercontent.com/assets/19224635/16486760/10f7ff46-3ec7-11e6-9c9e-8e87e17e2e25.png)

**Comment by nabilzhafri** [comment]
alright thanks for letting me know. seems like the path to the redis.json changed after the dist build (most probably because of concat files, etc. - and this changed the relative path to the redis.json) i'll try some other way :)

**Comment by distributev** [comment]
Thank you.

**Comment by nabilzhafri** [comment]
Hi there's a complication here. Since I'm following your path for redis.json, it causes the file not to be found when serve using `dist`.

The reason because when building for `dist`, `config` folder is not copied. Since I don't think you want to update gulp file, so please advice how to proceed.

gulp serve:

```
------- client
   ---- server
   ---- config (where redis.json located)
```

gulp serve:dist:

```
-------- client
    ---- server
(config folder is not copied)
```

**Comment by distributev** [comment]
How angularfullstack handle similar situations with different configuration file paths they need in production / dev. You said something about environment.js - is that related?

**Comment by distributev** [comment]
This was a question. 

How angularfullstack handle similar situations with different configuration file paths they need in production / dev?

**Comment by nabilzhafri** [comment]
its not related, thats about environment variables. the problem here is about the file itself. it doesn't exist in `dist` folder.
Since it's a new path/folder, `gulp` file needs to be updated so it'll copy it as well

**Comment by distributev** [comment]
Which existing gulp task you suggest to update in order to support the new path?

**Comment by nabilzhafri** [comment]
from what I see here:

```
gulp.task('serve:dist', cb => {
    runSequence(
        'build',
        'env:all',
        'env:prod',
        ['start:server:prod', 'start:client'],
        cb);
});
```

Most probably the build task. I think this is where its doing the optimisation and copied the output to dist folder.

**Comment by nabilzhafri** [comment]
any update on this one on how should I proceed? I would prefer not to touch the gulp configuration not to mess up with already working build config.

**Comment by distributev** [comment]
![redis](https://cloud.githubusercontent.com/assets/19224635/16542483/b2a1b60e-40aa-11e6-88c1-e52a178ae0fd.png)

**Comment by nabilzhafri** [comment]
hi, i did this according to your spec previously to use config/databases/redis.json.
are you saying we should ignore this spec and use the environment config now instead?

**Comment by distributev** [comment]
No. The spec remains the same redis.json will keep the redis configuration.

But the path to redis.json should not be hard-coded but instead should be configured development.js and production.js

See how the same is already done with the path to the sqllite3 database file. The path there it's not hard-coded.

Do the same here.

**Comment by nabilzhafri** [comment]
Hi, I don't think you understand how it works here.
The problem here is not the path, the problem here is the redis.json cannot be found since its not copied cover.

Even if I move the path to the development.js and production.js, the problem still remain since it cannot find the redis.json once build

**Comment by nabilzhafri** [comment]
check inside dist folder, you'll see development.js and production.js are copied over, since they're in server folder.
But custom config folder for redis.json is not there. So no point of moving the config to the development.js and production.js

**Comment by nabilzhafri** [comment]
The **ONLY** solution here without changing the gulp file is to move redis connection configuration into development.js and production.js and **not** redis.json inside config/databases.

**Comment by distributev** [comment]
In package-app project gulp file will get some additional custom tasks to package the app in a specific format - https://github.com/distributev/package-app (as part of package-app project all the required custom folders/files - including /config/ will be copied / packaged)

In our current kue-jobs project we only need to remove existing hard-codings - removing hard-codings will not only fix the current gulp serve:dist issue but will make smoother the way of any kind of custom packaging / deploying (for instance the package-app will be smoother without hard-codings / deploying to heroku will be smoother, aws deployment, etc, etc.)

Hard-codings are not good.

**Comment by distributev** [comment]
Let me try to explain with more details my approach. Please tell me if this is possible.

Currently, for sqllite3 in development.js you find

// Bookshelf connection options
 bookshelf: {
   filename: './dev.sqlite'
 }

and in production.js 

bookshelf: {
    filename: './dist.sqlite'
 }

and then in sqldb index.js the database file path it's not hard-coded but it's referenced as 

connection: {
    filename: config.bookshelf.filename
  }

the database path in gulp serve will come as dev.sqlite and in gulp serve:dist will come dist.sqlite

Similarly with the redis.json in development.js you could do something like

redis: {
   database: '../../../config/databases/redis.json'
 }

and in production.js 

redis: {
   database: '../../../../config/databases/redis.json'
 }

and then in your code you will reference this like 

config.redis.database

which will come correctly in both gulp serve (development.js - '../../../config/databases/redis.json') and gulp serve:dist (production.js - '../../../../config/databases/redis.json')

Is this possible?

**Comment by nabilzhafri** [comment]
Hi, still I don't think you understand what's really going on here.
Let me repeat: the problem here is NOT the path, it's the redis.json is not there.

**Let me try explain:**

It doesn't matter either you directly refer to redis.json directly in your code or your environment file, cause eventually, there're referring to the **same file**

So you can either do this in your code:
`../../../config/databases/redis.json` ---> directly referring to redis.json

or:

`config = require('../../config/environment').redis` --> you see here we're using relative path to refer to environment config file (similar thing)

which contains the path:

```
{
  redis: "../../../config/databases/redis.json"
}
```

--> which basically referring to the **same** file as above

The purpose of environment config file here is **NOT** to solve path issue - BUT it is to provide ability to have different configurations for different environment, hence it's called environment config file

So, even after you move the path inside the environment file, the error will still persist, because again, the redis.json is **not there**

Here is the **current** dist structure after you build:

```
------ client
  |---- server
           |--- config
                  |----- environment ---> here it's trying to find redis.json, but it's not there??!
```

It'll **ONLY** work if the redis.json is copied over when build. which **supposed** to look like this:

```
------ client
  |---- server
           |--- config
                  |----- environment
  |---- config (missing folder)
          |---databases
                |---- redis.json
```

As you can see, config folder above is the missing folder in dist!

Phew, thats a very long explanation. I really hope you get what I meant.

**Comment by nabilzhafri** [comment]
And please stop referring I hard coded redis.json path, cause this is really **not the problem here**.
If you say I hard coded it, it's like you're saying by putting the path in config files are **also** hard coded.

**Comment by distributev** [comment]
I think I understand this. Unless I don't.

Please mind that in my above answer development.js - '../../../config/databases/redis.json' and production.js - '../../../../config/databases/redis.json' (one extra command ..) shows different paths corresponding to how the file is located in development and how the same file is located in production.

P.S - I understand why you insist with copying the config file. Because you think it's better development and dist (aka. production) to have identical folders/files structures. In our case the current /dist it's not really how the app is deployed in production. So I prefer sticking to the minimum required changes to get /dist working. If you check the https://github.com/distributev/package-app project (the real production deployment) the folder structure is again different from both dev and dist so that package-app project will (very soon) come all the extra custom gulp task required to achieve the custom production deployment.

In our kue-jobs case I think it's only a matter of pointing development.js to '../../../config/databases/redis.json' and production.js to '../../../../config/databases/redis.json' (one extra ..) to find the same existing  config/redis.json file.

**Comment by distributev** [comment]
Merging the package-app branch solved this.
