### ISSUE TITLE
40 - seed-various-type-of-data

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#21]
![40 - seed-various-type-of-data](https://cloud.githubusercontent.com/assets/19224635/16486831/78715f32-3ec7-11e6-8d25-3ae886ff2256.png)

**Comment by nabilzhafri** [comment]
im afraid this will be a bit difficult, because its not very straightforward to add job with different state.
To have different state, will have to process them.
Now that I think of it, we should come up with kue jobs processing and then only the directives.

But no worry, I probably can do quick dummy process. But note that there's no guarantee to seed all types - failed/complete seem to be easiest.

Will include this in next push.

**Comment by distributev** [comment]
Thank you for the 'quick dummy process'

**Comment by nabilzhafri** [comment]
Push to kue-jobs repo. Please take  a look :)

If you need more, just stop and relaunch the apps.

**Comment by distributev** [comment]
Seeding with various statuses if fine now.

As for duration I see some 333 and 444 - What are these? I can assume myself these are ms but the GUI should be user friendly and should show duration in a human readable format like '4 minutes and 33 seconds' or 'Less then a second' - I think in the project brief I suggested to use moment.js library in order to show "human friendly" time intervals (see if moment.js is able to do that).

**Comment by nabilzhafri** [comment]
Ah. I havent made duration as user friendly. Will update this in a bit :)

**Comment by nabilzhafri** [comment]
Note that I already use moment.js for other columns, but missed to enable for duration.

**Comment by nabilzhafri** [comment]
Pushed the updates. Please take a look.

Here's how it works now:
Started: based on started_at field. not all states have it, for example inactive has no started_at field, means started is empty (make sense)
Finished: based on updated_at field. only showed when states is either complete/failed
Duration: seems like only complete has this field. handled by kue
