### ISSUE TITLE
issue-when-app-is-not-used-for-a-period

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#28]
![issue-when-app-is-not-used-for-a-period](https://cloud.githubusercontent.com/assets/19224635/16540372/fee9bf2c-4062-11e6-8785-b5e35b05426f.png)

**Comment by nabilzhafri** [comment]
hmmm never experience this. im gonna try run the app and leave it for a while and come back to it to see if it happens to me as well

**Comment by nabilzhafri** [comment]
hi! managed to reproduce this error and already fixed it :)

Explanation:
My guess is it could be just a network issue since our redis connection here requires internet network, which causes failed connection as the error says.

I've added missing proper handling, which basically binding to error events to prevent uncaught exceptions (prevent node from crash). If this happens again, it'll log errors to console instead of crashed.

Good catch! please try again :)

**Comment by distributev** [comment]
OK...but what will actually happen with the app/GUI?

**Comment by nabilzhafri** [comment]
nothing, it'll just continue working as usual. If the networks come back, it should simply reconnect, since the ui has a refresh interval.

The refresh interval is the one that cause the crash here - it tries to refresh within interval, but couldn't since redis cant be connected - and node crash

But now should be okay since i've added error handling.
