### ISSUE TITLE
explain-where-bluebird-is-required

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#3]
Where is the following dependency used?

"bluebird": "^3.4.1"

**Comment by nabilzhafri** [comment]
bluebird is a promise module. see its usage here: sqldb/index.js

**Comment by distributev** [comment]
search for this 'Bookshelf uses its own copy of the "bluebird" promise library' - http://bookshelfjs.org

if bookshelf comes with bluebird bundled-in why it was required to add it again?

**Comment by distributev** [comment]
I am not necessarily saying to remove bluebird from package.json just to understand what 'Bookshelf uses its own copy of the "bluebird" promise library' means and, if we leave it there because it will probably be useful later, what are the changes of getting "conflicts" with the bookshelfjs built in version.

**Comment by nabilzhafri** [comment]
understand, let me explain :)

when creating module, we shouldn't depend on other packages to define the dependency for us, even though they have it. The reason because:
1) What if in the future bookshelfjs decides to change their implementation to use other promise module? This will cause our app to break, because we assume bookshelfjs to use bluebird which might not be the case
2) This tells us we explicitly tells our app to depend on bluebird as one of our app dependency. in the future, if we decide to use other promise module, we can do so and need to update our package.json to refer to the new module such as 'q' module

If you worry about "conflict", worry not, because in this case, the promise doesn't has anything to do with bookshelf and use solely for one of the methods. Plus, the way npm works is each package will have their own package version, in this case, bookshelfjs will refer to their own bluebird package version, and our app will refer to our own bluebird package. i.e. you can see in node_modules/bookshelfjs, they also have their own node_modules folder.

Hope that clears.
