### ISSUE TITLE
Files which are not related with the task at hand should not be modified

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#35]
Following files are not related with the current task - why following files were modified?

Please revert the changes for following files

client/app/app.constant.js
client/index.html
.gitignore

**Comment by luismanuel001** [comment]
Those were modified automatically when running gulp serve.

**Comment by distributev** [comment]
gulp serve command was run before also without leaking generated code on github. 
What is different now? Is there anything else which we need to fix in order not to leak generated code in the future also?

**Comment by luismanuel001** [comment]
Not sure why these are modified, maybe because of different versions of gulp dependencies between my development machine and the other developer's machine.

I'm running on the most recent versions of all tools and dependencies as specified on package.json, so I think these may not change again in the future.

**Comment by distributev** [comment]
Roll back all 3 files.

Because gulp is modifying / generating js files during build please make sure to push on github only hand-written code.

**Comment by luismanuel001** [comment]
ok will do
