### ISSUE TITLE
redis binaries?

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#38]
![redis](https://cloud.githubusercontent.com/assets/19224635/16597498/83200ac4-42f9-11e6-91a8-e7ae9eee6a40.png)

**Comment by luismanuel001** [comment]
the Logs folder is needed so redis-server.exe can pipe output and error logs to the corresponding log files, without those the redis server will fail to start on windows.

Those 2 .conf files are the default ones from the https://github.com/MSOpenTech/Redis binaries, and they are also required in order to start the server.

We don't really need redis.windows.service.conf, since we are not using the redis-windows built in service functionality, so I can remove this one.

**Comment by distributev** [comment]
OK - remove what is not required.
