### ISSUE TITLE
blank-screen

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#42]
I get a blank screen instead of login
The console shows no error or other message.

![blank-screen](https://cloud.githubusercontent.com/assets/19224635/16630223/cbb74836-43b9-11e6-9909-282746035797.png)

**Comment by luismanuel001** [comment]
This is the issue I was talking to you about since I started working on this.  I think it has to do with the js minification and AdminLTE, if you open the js console you will see an error there.

This was even showing on the the-app original app when running gulp serve:dist, before I merged all my code, so it doesn't have anything to do with my changes.

**Comment by distributev** [comment]
How did you test your work then?
Did you see the application running with startApp.bat?
Did you install and see the windows services running?

**Comment by luismanuel001** [comment]
If you see the gray screen, it means it is actually serving it correctly on the 8080 port, so the node server s working fine.  You can also open the Windows "Services" tool and you will see the theappservice.exe service running. and you can test for the redis server with the redisServer.bat script.

**Comment by nabilzhafri** [comment]
Similar with #27. You can merge them.

Anyway, just pushed a fix for this issue. Please verify. Thanks!

**Comment by distributev** [comment]
gulp serve:dist is still returning a blank screen - 

did you see this comment?

_I think it has to do with the js minification and AdminLTE, if you open the js console you will see an error there._

**Comment by nabilzhafri** [comment]
Woops, I forgot to test `gulp serve:dist`. My bad.
Yeah there was an error when `gulp serve:dist` but it is now should be fixed.
