### ISSUE TITLE
change only files related with the task at hand 

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#58]
how is .yo-rc.json file related with current task? 

why it was changed?

**Comment by luismanuel001** [comment]
This is the yeoman configuration file that should have been created when initially scaffolded the angular-fullstack app.  This file is needed to use the yeoman angular-fullstack generators, and when I,  for example, ran "yo angular-fullstack:directive contact-details" it was failing because this file was missing. So I added so one can use the angular-fullstack generators.
