### ISSUE TITLE
 gulp serve:dist?

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#67]
I saw most of the hexo gulp changes target gulp serve command

What about gulp serve:dist?

**Comment by luismanuel001** [comment]
gulp serve:dist calls 'build' on its pipeline https://github.com/distributev/the-app/blob/frontend2/gulpfile.babel.js#L461, and thats where the other hexo tasks where added (as you described on the requirements), which I think is the correct location for those anyways.

**Comment by distributev** [comment]
I'm referring that gulp serve:dist (on the /client) it's also doing some obfuscation / minification / concatenation of the /client js/css/images files - 

Is the new /frontend part of this "dist" obfuscation / minification / concatenation pipeline?

**Comment by luismanuel001** [comment]
No it is not, the /frontend is mostly a regular hexo setup, the only extra thing added was the bower injection of dependencies added through bower.json, since the other obfuscation / minification / concatenation was not specified as a requirement, and I always tried to change only the necessary files on the hexo theme as you requested.

**Comment by distributev** [comment]
You are right here. It's actually better to keep hexo output with minimum modification possible.
