### ISSUE TITLE
another-runtime-error

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#9]
![another-runtime-error](https://cloud.githubusercontent.com/assets/19224635/16264114/e9de9e7e-3877-11e6-8ae4-9d2b149eab26.png)

**Comment by nabilzhafri** [comment]
This is expected, when running in deployment, because in development, it automatically add admin user & test user.

Let me explain:
When you run the app for the first time, it'll create admin and test user, say:

```
admin with id = 1
test with id = 2
```

Let's say if you log in with admin id = 1, it'll store your session user_id = 1. But if you stop your app, and do another `gulp serve`, it'll remove all previous users (reset), and automatically add admin user and test user again, but this time, with different id:

```
admin with id = 3
test with id = 4
```

This time, because it cannot find user with id = 1, that's why it shows error means cannot find the user.

Note that this is original behavior, I'm not sure how to change/handle this. To me the error is correct.
In production, this **won't happen** since user won't be deleted and automatically added on app start.

**Comment by distributev** [comment]
OK - for now you can close this issue.

I might re-open again the same later if I will find this was not the case.

**Comment by nabilzhafri** [comment]
Sure thing. If you found something similar, but not like this case, please let me know.

**Comment by nabilzhafri** [comment]
Hi there,
I've updated the code to make it show 401 status code (Unauthorized) instead of showing error :) I guess this'll look nicer to you.
`GET /api/users/me 401 49.214 ms - -`

Underlying they remain the same as I explained above.
